// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojz1RAkKtJdg4YuQOe2qa92YY9hRqGaI',
    appId: '1:381597151620:web:4e5649901d4bc85e9e6dd1',
    messagingSenderId: '381597151620',
    projectId: 'todo-5d207',
    authDomain: 'todo-5d207.firebaseapp.com',
    storageBucket: 'todo-5d207.appspot.com',
    measurementId: 'G-M9PJ2Q1KKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKv1PNpLEyhV1OpPLIqX51qFurusqdCQ',
    appId: '1:381597151620:android:37b5b3cafaf5ca179e6dd1',
    messagingSenderId: '381597151620',
    projectId: 'todo-5d207',
    storageBucket: 'todo-5d207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrTsogWnERkkuNTrME5n1GwEsrWNwFsE',
    appId: '1:381597151620:ios:6e62a45cd75e17889e6dd1',
    messagingSenderId: '381597151620',
    projectId: 'todo-5d207',
    storageBucket: 'todo-5d207.appspot.com',
    iosBundleId: 'com.example.firebaseScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmrTsogWnERkkuNTrME5n1GwEsrWNwFsE',
    appId: '1:381597151620:ios:a0b14f0eb258bfc89e6dd1',
    messagingSenderId: '381597151620',
    projectId: 'todo-5d207',
    storageBucket: 'todo-5d207.appspot.com',
    iosBundleId: 'com.example.firebaseScreen.RunnerTests',
  );
}
